environment = "prod"
# lambda_role_arn             = "arn:aws:iam::377740208333:role/service-execution-iam-role"
# clp-endpoint                = "http://submit.log-stg.factset.com:21102"
# clp-index                   = "test"
# ogg-endpoint                = "/api/v1/ogg"
ogg-api-url                 = "http://internal-callst-dam-api-536324289.us-east-1.elb.amazonaws.com"
# ogg-upload-deadletter-queue = "module.sqs.ogg-upload-tasks-deadletter-url"
# ogg-upload-queue            = "module.sqs.ogg-upload-tasks-url"
